### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by multiwebinc**
Rewrite using flat theme, get rid of jquery-mobile, add jquery-ui and bootstrap, change localStorage to chrome.storage when possible.

### CODE REVIEW

**Comment by gbraad** [comment]
I will reserve time to review these changes soon...

**Comment by gbraad** [comment]
Some small remarks:

  * gauth.js, line 46: Why is there a ", callback" in the if statement?
  * indentation is not consistent
  * it assumes Chrome users always want to use chrome.storage. This means I can not publish it at the moment as a hosted option as this would not work for current users of Chrome and users of the old Chrome extension (at least 2k+).
  * unused references to $.mobile and unused libraries in /lib

I will implement part of the solution by cherry-picking... but will review what to do with the Chrome storage. The idea is good, but probably needs me to implement an export/import/sync/transfer from localStorage to Chrome Storage and allow the user to configure this behaviour.

**Comment by gbraad** [comment]
Flat style will be incorporated in the next push with some small changes as the shown keys are a little small when reading from a mobile device.

**Comment by multiwebinc** [comment]
I didn't think about existing users of Chrome. That's a very good point. I think it would be best to have a separate settings page with all of the available options, such as choosing which storage backend to use (and allow copying of existing entries if the user changes it), adding, editing and deleting entries, import/export of data, and the about page. So on the main page would just be the list of accounts and a link to the settings. This is something I could work on next week including the fixes to the other problems mentioned above. What do you think?

**Comment by gbraad** [comment]
The merge would also have failed for

```javascript
if (typeof (chrome.storage) !== "undefined") {
    return "chrome";
}
```

as for any other browser (Safari, Firefox, Opera, etc) this would result in the chrome object being undefined and the application fails to load.

Bootstrap itself should be quite usable on mobile devices, however in your styling you have hard-coded width in pixel dimensions. This was not an easy-fix and therefore I have update the styling to use a newer version of jquery mobile. This was a 5-minute fix and it even reduced the loading time as less files were needed. I might consider updating this later to something else... for now, I am more concerned about compatibility.

**Comment by multiwebinc** [comment]
Man... that really takes the proverbial wind out of my sails.

**Comment by gbraad** [comment]
The biggest problem is that fact that Chrome changed from the a new v2 manifest. The newer extensions are not allowed to use localStorage at all. This messes things up badly. The user will not be able to select at all as localStorage is not allowed... and Chrome storage can only be used in the context of the new manifest. An export solution seems to be the only way forward for now as syncing is not possible.

About the styling... I will use bootstrap later, but the design was fixed on pixel coordinates. This is unusable when it comes to mobile and even HiDPI situations (when no scaling is used). I started to remove these fixed values in your changeset, but didn't have enough time to finish it.

**Comment by multiwebinc** [comment]
Well I would really like to continue to help with the project and since localStorage will not be allowed in Chrome extensions I would assume is all the more reason to use chrome.storage in Chrome extensions eventually. Actually that was the main reason I wanted to contribute to this project because I know that localStorage doesn't sync, but chrome.storage does. This would even partially make import/export unnecessary for Chrome since many people would just need to connect their Google account to their browser and have it sync everywhere, which is quite a bit easier than trying to fiddle around with files.

Anyway, as I mentioned before, I think that the best thing to do would be to create a separate page for settings and in there would be an import/export section. I could work on coding that this week. I don't think it would be overly hard. I already had the menu designed (using Bootstrap navbar) and no pixel dimensions.

As for the main page, I spent 20 minutes or so and made the OTPs use em instead. It works just fine on a desktop computer, but if that doesn't work for mobile, what is the preferred way to make a width not based on percent or pixels? Or is it required to be one of these two units? Also, the first declaration I have:

    html {
      min-width: 550px;
      min-height: 400px !important;
    }

It is necessary to set width and height of html or else the pop-up in the Chrome extension has no dimensions (or maybe it was something really small, I can't quite remember). Is this fine? Or is there another preferred way to do this so that it works on mobile browsers too?

Let me know how you would like me to continue because I wouldn't want to waste my time doing anything else that wouldn't be included. Do you want me to fix any of the errors in my current pull? They are mostly trivial.

**Comment by gbraad** [comment]
Current styling in Firefox OS without additional work:
skew

**Comment by gbraad** [comment]
I have taken up the idea of doing a packaged app for Firefox OS and with this also the packaged extension for Chrome would be available. This means the need for a changeable storage backend is important.

At the moment I also do not have a lot of time, but I'll try to see what I can do... at least a export and import are of a higher priority as this allows moving between OS and platform easier.

**Comment by multiwebinc** [comment]
Actually, the manifest file I added makes this available as a Chrome extension.

**Comment by gbraad** [comment]
I am aware of this... however I  would trigger the extension as a background script
  * https://github.com/gbraad/html5-google-authenticator/blob/chrome/manifest.json
  * https://github.com/gbraad/html5-google-authenticator/blob/chrome/js/chrome_app.js

instead of a page action. This way you can set dimensions. Why the page action?

The reason why I do not incorporate these changes is because without addressing the style and some other coding issues I would have to maintain a separate codebase. Feature detection is very important... I have (many) existing users.

**Comment by multiwebinc** [comment]
I am working on an updated pull request. I am sure you will like it much more. When I did the original one I was only taking Chrome into account.

**Comment by multiwebinc** [comment]
OK, I hope you like this.

- I decided to get rid of jQueryUI and just use the Bootstrap JS since I needed it anyway.
- I updated all measurements to use `em` instead of `px` (except for any that were included in Bootstrap by default)
- I added a settings page separate from the main page. The main page is now *only* for getting the OTP. Everything else is in settings.
- It now allows users to use either chrome.storage or localstorage. If something is in localstorage, it won't force them to move to chrome.storage. The menu option only shows up when using chrome extensions because in any other case localStorage is the only option (I think).
- Export and import functionality
- AES encryption
- Account editing

**Comment by multiwebinc** [comment]
Oh, there are two (probably important) things I forgot to do:

- Prompt for the passphrase if it is not available in `localStorage`
- Delete the passphrase from `localStorage` when the browser window is closed.

I am not exactly sure what the best way to handle this is, but I just stored the passphrase in localStorage in plain text. This should **not** be stored indefinitely. And possibly there should be some sort of locking mechanism in case someone wants to purposely lock it. Also, for the Chrome extension (I'm not sure how FF works), I think that we should use a background page or else every time the extension is closed the user will have to reenter their passphrase.

**Comment by multiwebinc** [comment]
Also, again I probably messed with the indentation, but I was at least consistent (4 spaces for JS, 2 spaces for HTML and CSS). If you want to change it, go ahead. Or I can change it if you want. Just let me know how you want it in all 3 file types.

**Comment by gbraad** [comment]
never store the used AES passphrase with the encrypted data... not even to
decrypt it... the logic should not even be aware if the correct passphrase
was used.

I would always timeout the key after navigating away or leaving the page
unattended for some time. It might be less user-friendly, however this is
how most iOS applications work (a passphrase/keylock screen gets triggered
on app activation).

On Thu, Jan 15, 2015 at 2:47 PM, multiwebinc <notifications@github.com>
wrote:

> Oh, there are two (probably important) things I forgot to do:
>
>    - Prompt for the passphrase if it is not available in localStorage
>    - Delete the passphrase from localStorage when the browser window is
>    closed.
>
> I am not exactly sure what the best way to handle this is, but I just
> stored the passphrase in localStorage in plain text. This should *not* be
> stored indefinitely. And possibly there should be some sort of locking
> mechanism in case someone wants to purposely lock it. Also, for the Chrome
> extension (I'm not sure how FF works), I think that we should use a
> background page or else every time the extension is closed the user will
> have to reenter their passphrase.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gbraad/html5-google-authenticator/pull/55#issuecomment-70046425>
> .
>



-- 
Gerard Braad — 吉拉德
   F/OSS & IT Consultant in Beijing
   http://gbraad.nl  gpg: 0x592CFE75

**Comment by multiwebinc** [comment]
I just found another issue disabling/enabling sync with encrypted accounts. Disabling sync json encodes the encrypted string, which it shouldn't. And manually editing the string to get rid of the quotation marks around it and re-enabling sync doesn't work either. Blegh. At least I hope this is a decent foundation that you can work from.

**Comment by mcepl** [comment]
> localStorage will not be allowed in Chrome extensions

WTF? Anyway, that's not mine problem. Just please make sure you are not doing this app to be The Best Viewed with Chrome™. I am on Firefox OS and I know plenty of people who use this app on Firefox as well.

**Comment by gbraad** [comment]
@mcepl Same thought here...

No Local Storage is for me almost a reason to avoid Chrome extensions
entirely. I am concerned about the privacy and security issues when syncing
is almost implied. Many users I have are concerned about the security
implications...

**Comment by multiwebinc** [comment]
Do you have any documentation or references from Google about that? I did a quick search just now and couldn't find anything at all. This page https://developer.chrome.com/extensions/storage references localstorage but does not say that its use is discouraged or that it is deprecated.  

For many reasons it doesn't even make sense to me that they would do that. Then again, Chrome devs tend to not listen to the people...

**Comment by gbraad** [comment]
"window.localStorage is not available in packaged apps. Use chrome.storage.local instead."

disallowed

**Comment by multiwebinc** [comment]
I don't get it. Why did I not get that error?

**Comment by gbraad** [comment]
Because you are not using the localStorage API and probably did not execute any of that code. Sync and LocalStorage are different things...

https://developer.chrome.com/extensions/storage#method-StorageArea-get

chrome.storage.local.set({'someItem': 'some value'});
chrome.storage.local.get('someItem', function (result) { });

**Comment by multiwebinc** [comment]
I am certainly using localStorage. You need to look at my new and improved code in the last push. It wouldn't be hard to add chrome.storage.local as well since the syntax is the same as chrome.storage.sync.

**Comment by multiwebinc** [comment]
You said you wanted to get rid of jQuery Mobile and implement a flat theme, which I did in changing to Bootstrap and then in your master you decided to keep jQuery Mobile. You mentioned that my original push would not be compatible with current users, so I fixed that too as well as all of the other errors you mentioned. I really put a lot of work into this and I would appreciate if you could please review this code and let me know what you want me to do. I am afraid that we are working more and more in two different directions and one of us (almost definitely me) is wasting our time having to do things twice. You've done a bunch of stuff to the master branch since I posted this that make this slightly incompatible. It's nothing that can't be fixed relatively easily, but we need to get on the same page soon or it will become more and more difficult. You're the repository owner, so let me know what you want me to do, but please make a decision and stick with it. If you want to keep jQuery Mobile, that's fine. If you would prefer to use what I have with Bootstrap, fine as well. Or if you would prefer for me to adopt a similar hamburger menu style, that shouldn't be a problem either. I just need to know what your thoughts are so that we're not wasting our time here.

**Comment by gbraad** [comment]
First, I have not mentioned getting rid of jQuery Mobile. It might not be ideal, but it does the job. I might not need a framework, but is what I got and have to deal with for now. You never contacted me beforehand what your idea was. Your work is well-intended, and I thank you for this... but it unusable/unmergable when considering the current use-case. My current users are on so many other browsers and devices; Tizen, MeeGo, WebOS, Blackberry, Nokia, Firefox OS, Android, Opera, Safari, iOS, UC, and more... Working with Application Cache is a PITA to deal with. If you want to contribute, please at least test in Firefox and Chrome, before pushing... So second, small incremental changes are more likely to get added/merged. Big bangs only work in a well coordinated fashion. This is just one of the projects I work on, it is dear to my heart, but also just a small side-project. And testing takes a lot of time... Almost every change I have to test on multiple devices and environments before I push them. My thoughts are all described in the issues tracker... discuss issues separately.

**Comment by multiwebinc** [comment]
> You never contacted me beforehand what your idea was.

Actually I contacted you by email. I noticed that it lacked a Chrome extension, and what I was really interested in is getting the accounts to sync between devices, which is available with chrome.storage, so I took the liberty of converting it to use chrome.storage. My intention was to only to provide you with a Chrome extension version of your code that could be added to the Chrome app store, but I did not realize that it needed to share code with other devices. My mistake.

> I have not mentioned getting rid of jQuery Mobile

In fact you did mention getting rid of jQuery Mobile in the same email:

> I was actually going to drop jQuery Mobile... or at least change the
style to a more 'flat'-style as this fits better with  the mobile
phone users and new browsers out there.

Anyway, since I have done a lot of the work already, what is the best way to get at least some of what I have done integrated? Again, my main interest is getting chrome.storage so that the accounts can be synced. I am a Github noob and I don't know the best way to collaborate on projects. Can you assign bugs to me based on the changes made with this pull request? If not, what do I do? Please be specific.

**Comment by gbraad** [comment]
A single commit or some commits should change a feature as a whole. this way it is easier to track the changes that occurred and pinpointing issues that might come out of them. The commits themselves should each be working code. If you know an issue exists, the following commit should resolve this. Never hand something over something with an issue... drop the commit from the pull request that introduced it or indicate which change it was. Also, test every change with more than one version of the browser, the last, recent and new release when possible. For Firefox at the moment, 33, 34 and 36 are good candidates and for Chrome using the latest Stable and Canary build. Any commit that fails `npm test` and incorrectly deals with AppCache will be denied. At the moment I will reconsider the known issues and see if outside contribution is needed. Yes, a Chrome extension will follow soon... and I will look at the changes you made for this, but I can not commit to a timeframe...

**Pull request closed without merging**
